name = "r2-file-manager"
main = "src/index.js"
compatibility_date = "2024-01-01" # 使用一个较新的兼容性日期

# 绑定 R2 存储桶
[[r2_buckets]]
binding = 'MY_BUCKET' # 在 Worker 代码中将使用 env.MY_BUCKET 访问，在 Worker 代码中使用的环境变量名，请保持为 'MY_BUCKET'
bucket_name = 'r2-test' # 您的 R2 存储桶的实际名称

# 定义 Secret，用于存储密码
# 使用 wrangler secret put AUTH_KEY_SECRET 命令设置实际值
# 在 Worker 代码中将通过 env.AUTH_KEY_SECRET 访问
# secrets = [
#   "AUTH_KEY_SECRET"
# ]